### ISSUE TITLE
False positive on objectscriptquality:OS0091 ?

### ISSUE THREAD

**Issue by jpa95** [litesolutions/objectscriptquality-vscode#6]
The following SqlProc gets flagged because of the use of quotes in naming the column "data", which i belive is legal.

```
Query SqlProc(lstUeid As %String) As %SQLQuery
{
SELECT fakeTable."data"
  FROM (SELECT '1' AS data) AS fakeTable
}
```
Before i deactivate the rule, I would like an expert opinion, thanks!

**Comment by daimor** [comment]
yes, write it as `"data"` is totally legal, but the purpose of using `"` sign in IRIS SQL is to be able to use reserved words 

if you change data to date, in this case you would have to use `"date"` form , instead of plain `date`

While the syntax is legal, the purpose of syntax analyzing is to support a style in code, and the purpose of this particular rule, is, do not let to use reserved keywords in IRIS SQL, which makes of writing SQL queries a bit more difficult when developer forgets to use `"`

So, the rule works totally fine, as it's intended.

**Comment by jpa95** [comment]
To make sure I understand -- What you are saying is that we should not be using keywords in our IRIS SQL, and those keywords require the " (for example if a column is named "date" or "type"), is that it?

Thanks for the quick answer! By the way I love the tool, it is very helpful.

**Comment by daimor** [comment]
Right, this is the idea of the rule

Thanks
